capture program drop Update_Varlist
program define Update_Varlist
	local path $estdb_path
	assert_msg `"`path'"'!="",  msg("Path not set. Use -estdb setpath PATH- to set the global estdb_path") rc(101)
	conf file "`path'/varlist_template.dta"

	* Backup if possible
	cap copy "`path'/varlist.dta" "`path'/varlist_backup.dta", replace
	cap copy "`path'/varlist.tsv" "`path'/varlist_backup.tsv", replace

	* Load preset varlist if it exists (tab-separated for easier editing)
	cap conf file "`path'/varlist.tsv"
	if !_rc {
		qui import delimited "`path'/varlist.tsv", clear delim("\t") ///
			varnames(1) case(preserve) asdouble stringcols(1 2 3) numericcols(4 5)
		tempfile existing
		qui save "`existing'"
		use "`path'/varlist_template", clear
		qui merge 1:1 varname using "`existing'", keep(master match match_update) nogen nolabel nonotes update
	}
	else {
		qui use "`path'/varlist_template", clear
	}
	la data "ESTDB Table Labels - AUTOGENERATED FILE, don't update directly"
	qui save "`path'/varlist", replace

	* Export so it can be updated
	local fn "`path'/varlist.tsv"
	qui export delimited "`fn'", replace nolabel delim(tab) quote
	
	*di as text "estdb: update done, you can edit " as result "`fn'"
	di as text "estdb: update done, you can now edit " _c
	di as smcl `"{stata "shell `fn'":`fn'}"'
	clear
end

